#!/usr/bin/env python3

#Function get params (in this case is port) passed via WATO agent rule configuration: hostname and ip of host
def agent_foldingathome_arguments(params, hostname, ipaddress):
    args = []

    args += ["-i", ipaddress]
    args += ["-p", params['port']]
    auth = params.get('auth', '')
    args += ["-a", auth]

    return args

#register invoke function for our agent
#key value for this dictionary is name part from register datasource of our agent (name="special_agents:myspecial")
special_agent_info['foldingathome'] = agent_foldingathome_arguments
